default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  min_messages: warning
  timeout: 5000
  username: root
  password:

development:
  <<: *default
  database: wgt_notify_turow_development

test:
  <<: *default
  database: wgt_notify_turow_test

production:
  <<: *default
  host: <%= Rails.application.credentials.production[:host] %>
  database: <%= Rails.application.credentials.production[:database] %>
  username: <%= Rails.application.credentials.production[:user] %>
  password: <%= Rails.application.credentials.production[:password] %>

