default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  min_messages: warning
  timeout: 5000
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: gs_software_development

test:
  <<: *default
  database: gs_software_test

production:
  <<: *default
  database: gs_software_production
  username: gs_software
  password: <%= ENV['GS_SOFTWARE_DATABASE_PASSWORD'] %>
