common: &default_settings
  log_level: info
  license_key: <%= Rails.application.credentials[:new_relic_key] %>

development:
  <<: *default_settings
  monitor_mode: false

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  app_name: PGE Turów - awizacja ważeń (Staging)

production:
  <<: *default_settings
  app_name: PGE Turów - awizacja ważeń (Production)
