common: &default_settings
  license_key: <%= Rails.application.credentials.production[:new_relic_key] %>
  app_name: PGE Turów - awizacja ważeń
  log_level: info


development:
  <<: *default_settings
  app_name: PGE Turów - awizacja ważeń (Development)

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  app_name: PGE Turów - awizacja ważeń (Staging)

production:
  <<: *default_settings
